/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Kelas.Kategori;
import Kelas.TimedJOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizan
 */
public class MenuKategori extends javax.swing.JPanel {

    /**
     * Creates new form MenuKategori
     */
    public MenuKategori() throws SQLException {
        initComponents();
        loadTabel();
        autoId();
        reset();
    }

    void loadTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(null);
        model.addColumn("Kode Kategori Surat");
        model.addColumn("Nama Kategori Surat");

        try {
            Kategori k = new Kategori();
            ResultSet data = k.KodeTampil();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("id"),
                    data.getString("kode_kategori"),
                    data.getString("nama_kategori"),});
            }

            data.close();
        } catch (SQLException sQLException) {
        }

        tb_Kategori.setModel(model);

        tb_Kategori.getColumnModel().getColumn(0).setMinWidth(0);
        tb_Kategori.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_Kategori.getColumnModel().getColumn(0).setWidth(0);

    }

    void reset() {
        tf_Kode.setText(null);
        tf_Nama.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_Id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_Kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Kategori = new javax.swing.JTable();
        bt_Tambah = new javax.swing.JButton();
        bt_Ubah = new javax.swing.JButton();
        bt_Hapus = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        pn_Main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Menu Kategori Surat");

        jLabel2.setText("Kode Kategori");

        jLabel3.setText("Nama Kategori");

        tb_Kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_Kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_KategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Kategori);

        bt_Tambah.setText("Tambah");
        bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TambahActionPerformed(evt);
            }
        });

        bt_Ubah.setText("Ubah");
        bt_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UbahActionPerformed(evt);
            }
        });

        bt_Hapus.setText("Hapus");
        bt_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_MainLayout = new javax.swing.GroupLayout(pn_Main);
        pn_Main.setLayout(pn_MainLayout);
        pn_MainLayout.setHorizontalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                    .addGroup(pn_MainLayout.createSequentialGroup()
                        .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(pn_MainLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Nama)
                                    .addGroup(pn_MainLayout.createSequentialGroup()
                                        .addComponent(bt_Tambah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_Ubah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_Hapus)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pn_MainLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_Kode))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_MainLayout.setVerticalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lb_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Tambah)
                    .addComponent(bt_Ubah)
                    .addComponent(bt_Hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pn_Main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TambahActionPerformed
        try {

            Kategori kodeTambah = new Kelas.Kategori();
            kodeTambah.setId(Integer.parseInt(lb_Id.getText()));
            kodeTambah.setKode_kategori(tf_Kode.getText());
            kodeTambah.setNama_kategori(tf_Nama.getText());
            kodeTambah.KodeTambah();
            loadTabel();
            reset();
            autoId();

        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bt_TambahActionPerformed

    private void bt_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UbahActionPerformed
        try {

            Kategori kodeUbah = new Kategori();
            kodeUbah.setId(Integer.parseInt(lb_Id.getText()));
            kodeUbah.setKode_kategori(tf_Kode.getText());
            kodeUbah.setNama_kategori(tf_Nama.getText());
            kodeUbah.KodeUbah();
            loadTabel();
            reset();
            autoId();

        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bt_UbahActionPerformed

    private void bt_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HapusActionPerformed
        try {

            if (lb_Id.getText().isEmpty()) {
                TimedJOptionPane timedPane = new TimedJOptionPane();
                timedPane.showTimedMessage("Pilih data yang ingin dihapus!", null, JOptionPane.WARNING_MESSAGE, 1000);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Yakin ingin menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                Kategori kodeHapus = new Kategori();
                kodeHapus.setId(Integer.parseInt(lb_Id.getText()));
                kodeHapus.KodeHapus();
                loadTabel();
                autoId();
                reset();

            }
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bt_HapusActionPerformed

    private void tb_KategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_KategoriMouseClicked
        int baris = tb_Kategori.rowAtPoint(evt.getPoint());
        String id = tb_Kategori.getModel().getValueAt(baris, 0).toString();
        String kode = tb_Kategori.getValueAt(baris, 1).toString();
        String nama = tb_Kategori.getValueAt(baris, 2).toString();

        lb_Id.setText(id);
        tf_Kode.setText(kode);
        tf_Nama.setText(nama);
    }//GEN-LAST:event_tb_KategoriMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Hapus;
    private javax.swing.JButton bt_Tambah;
    private javax.swing.JButton bt_Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Id;
    private javax.swing.JPanel pn_Main;
    private javax.swing.JTable tb_Kategori;
    private javax.swing.JTextField tf_Kode;
    private javax.swing.JTextField tf_Nama;
    // End of variables declaration//GEN-END:variables

    private void autoId() throws SQLException {
        Kategori auto = new Kategori();
        int newID = auto.autoIdKategori();
        lb_Id.setText(String.valueOf(newID));
    }

}
